spring.application.name=beachhouse-api
spring.profiles.default=dev

spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info

spring.jpa.defer-datasource-initialization=false
spring.flyway.locations=classpath:db/migration
